/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nugrahanto
 */
public class Mainpage extends javax.swing.JFrame {

    String nol_jam = "";
    String nol_menit = "";
    String nol_detik = "";
    
    public Mainpage() {
        initComponents();
        selectData();
        selectData2();
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTanggal = new javax.swing.JLabel();
        jLabelJam = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBarang = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        txtHarga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblData1 = new javax.swing.JTable();
        jButtonSave = new javax.swing.JButton();
        txtJmlBarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JDateChooser = new com.toedter.calendar.JDateChooser();
        jButtonClear = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(null);

        jLabelTanggal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTanggal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTanggal.setText("TANGGAL");
        jPanel1.add(jLabelTanggal);
        jLabelTanggal.setBounds(700, 50, 160, 20);

        jLabelJam.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelJam.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJam.setText("JAM");
        jPanel1.add(jLabelJam);
        jLabelJam.setBounds(720, 70, 160, 20);

        jLabel8.setFont(new java.awt.Font("Minion Pro SmBd", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MINIMARKET");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(120, 10, 270, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("THE REAL INFORMATICS SCHOOL");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(120, 50, 260, 20);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon("E:\\MOKLET\\XI\\PBO\\Project\\TestCRUD\\gambar\\ts.png")); // NOI18N
        jPanel6.add(jLabel10);
        jLabel10.setBounds(20, 10, 60, 80);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 0, 100, 100);

        jLabel11.setFont(new java.awt.Font("Minion Pro SmBd", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SMK TELKOM MALANG");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(120, 30, 270, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 950, 100);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAMA");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 100, 14);
        jPanel2.add(txtnama);
        txtnama.setBounds(20, 30, 150, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BARANG");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 110, 100, 14);

        txtBarang.setEditable(false);
        jPanel2.add(txtBarang);
        txtBarang.setBounds(20, 130, 150, 25);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_transaksi", "nama", "id_barang", "nama_barang", "harga_barang", "jumlah_barang", "tanggal", "total_harga"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblData);
        if (tblData.getColumnModel().getColumnCount() > 0) {
            tblData.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(200, 130, 730, 200);

        txtHarga.setEditable(false);
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        jPanel2.add(txtHarga);
        txtHarga.setBounds(20, 180, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HARGA");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 160, 100, 20);

        txtId.setEditable(false);
        jPanel2.add(txtId);
        txtId.setBounds(20, 80, 150, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 60, 100, 14);

        tblData1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id_barang", "nama_barang", "harga_barang"
            }
        ));
        tblData1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblData1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblData1);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(360, 20, 380, 80);

        jButtonSave.setBackground(new java.awt.Color(204, 0, 0));
        jButtonSave.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSave.setText("SAVE");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSave);
        jButtonSave.setBounds(20, 360, 80, 25);
        jPanel2.add(txtJmlBarang);
        txtJmlBarang.setBounds(20, 240, 150, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TANGGAL");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 280, 130, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BANYAK BARANG");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 220, 130, 14);
        jPanel2.add(JDateChooser);
        JDateChooser.setBounds(20, 300, 150, 25);

        jButtonClear.setBackground(new java.awt.Color(204, 0, 0));
        jButtonClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClear.setText("CLEAR");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonClear);
        jButtonClear.setBounds(110, 360, 80, 25);

        jButtonPrint.setBackground(new java.awt.Color(204, 0, 0));
        jButtonPrint.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrint.setText("PRINT");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPrint);
        jButtonPrint.setBounds(510, 350, 80, 25);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 950, 430);

        setSize(new java.awt.Dimension(969, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDataMouseClicked

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void tblData1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblData1MouseClicked
        // TODO add your handling code here:
        int baris = tblData1.getSelectedRow();
        if (baris != -1) {
            txtId.setText(tblData1.getValueAt(baris, 0).toString());
            txtBarang.setText(tblData1.getValueAt(baris, 1).toString());
            txtHarga.setText(tblData1.getValueAt(baris, 2).toString());
        }
    }//GEN-LAST:event_tblData1MouseClicked

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd--MM--yyyy");
        String tanggal = dateFormat.format(JDateChooser.getDate());
        
        int harga = Integer.parseInt(txtHarga.getText());
        int jumlah = Integer.parseInt(txtJmlBarang.getText());
        int hargatotal = harga * jumlah;
        
        if (txtnama.getText().equals("")|| 
            txtId.getText().equals("")||
            txtBarang.equals("")||
            txtHarga.getText().equals("")||
            txtJmlBarang.getText().equals("")||
            tanggal.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else{

            String SQL = "INSERT INTO tb_transaksi (nama,id_barang,nama_barang,harga_barang,jumlah_barang,tanggal,total_harga)"
            + "VALUES('"+txtnama.getText()+"','"+txtId.getText()+"','"+txtBarang.getText()+"','"+txtHarga.getText()+"','"+txtJmlBarang.getText()+"','"+tanggal+"','"+hargatotal+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData2();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        txtnama.setText("");
        txtId.setText("");        
        txtBarang.setText("");
        txtHarga.setText("");
        txtJmlBarang.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Transaksi Pembelian Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page {0,nimber,interger}  ");

        try {
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jButtonPrintActionPerformed

    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd-MM-yyyy");
        jLabelTanggal.setText("Tanggal :     "+kal.format(skrg));
    }
    
    public void setJam(){
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                int nilai_jam   = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                jLabelJam.setText("Jam :     "+jam + ":" + menit + ":" + detik);
            }
        };
        new Timer(100, taskPerformer).start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateChooser;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelJam;
    private javax.swing.JLabel jLabelTanggal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblData;
    private javax.swing.JTable tblData1;
    private javax.swing.JTextField txtBarang;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJmlBarang;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"id_barang","nama_barang","harga_barang"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_barang";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while (rs.next()) {
                String id_barang = rs.getString(1);
                String nama_barang = rs.getString(2);                
                String harga_barang = rs.getString(3);
                String data[] = {id_barang,nama_barang,harga_barang};
                dtm.addRow(data);
            }
        }catch (SQLException ex){
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData1.setModel(dtm);
    }

    private void selectData2() {
        String kolom[] = {"id_transaksi","nama","id_barang","nama_barang","harga_barang","jumlah_barang","tanggal","total_harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_transaksi";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while (rs.next()) {
                String id_transaksi = rs.getString(1);
                String nama = rs.getString(2);
                String id_barang = rs.getString(3);
                String nama_barang = rs.getString(4);                
                String harga_barang = rs.getString(5);
                String jumlah_barang = rs.getString(6);
                String tanggal = rs.getString(7);
                String total_harga = rs.getString(8);
                String data[] = {id_transaksi,nama,id_barang,nama_barang,harga_barang,jumlah_barang,tanggal,total_harga};
                dtm.addRow(data);
            }
        }catch (SQLException ex){
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);
    }
}
